package warriorlordsserv;

public enum Error
{
	NO_ERROR,

	SERVER_ERROR,
	INVALID_REQUEST,
	EXPECTED_ARGUMENTS,
	INVALID_ARGUMENTS,
	INVALID_USER,
	INVALID_GAME,
	INVALID_LOGIN,
	GAME_FULL,
	ALREADY_PRESENT,
	NOT_IN_GAME,
	UNABLE_TO_START_GAME,
	INVALID_ACTION
}
